# Hi. 

# Thanks for coming.

So, this is probably a  bit more normal of a session (I hope). Someone will give a small presentation reviewing the reading and talking about some new concept. That's all subject to change given group feedbcak though. We'll see how it goes today. 

Some of you may notice that this is a Jupyter Notebook. What I like about Jupyter Notebooks is that I can annotate my code in a clear and concise way. I'll first show you how to do what I am doing now. First, you want to start with a blank cell, like the one below. Notice the "In [ ]:", this means that it is a code cell. Thus, if you type code and run the cell, it will perform the tasks you ask it to. In order to change it to a markdown cell you can click on the cell, then go Cell -> Cell Type -> Markdown. You can also click into the cell, then use the dropdown menu at the top to change the cell to markdown. Alternatively you can go into "command mode" by clicking on the cell, then pressing Esc. You will know that you are in command mode because the cell wall will be blue. You can then press "m" to turn it into a markdown cell. You can change it back by pressing "y".  

There are all sorts of short cuts for Jupyter. To look at all of them you can enter command mode and press "h". If you'd prefer a bookmarked website, for Windows users I'd recommend: 

https://www.cheatography.com/weidadeyue/cheat-sheets/jupyter-notebook/

For Mac Users:

https://treehouse-code-samples.s3.amazonaws.com/Python/jupyter-shortcuts.pdf

If you're not familiar with Markdown, its like a simpler version of Latex. Here is a good resource for some common commands:

https://www.markdownguide.org/cheat-sheet/

You can also use symbols in both markdown and in your code, which is kind of cool. To type theta in markdown you will want to surround \theta by \$ signs

$\theta$

To use a greek letter in your code, you can just type \theta than press tab.

In [2]:
θ = 3
θ +2 

5

Lastly, who's bad at spelling? I am the worst. Jupyter does not have a built in spell check. To install one, open Anaconda prompt. Then enter these commands: 

pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable spellchecker/main

Then open Jupyter Notebooks and you should see the little abc button. This is an extension for spell check!

## Questions?

Radical. Let's move on to the reading review. Who did the reading? Nice. I figured a brief review of the major points would be useful. Don't feel pressured to read if you're busy. I encourage the presenter to always give a timely overview of the reading. 

# Chapter 1 - About Python

Python is important. People use it for a lot of stuff. 

We're going to use a lot of packages. Personally, I'm not sure the best way to deal with them. I'm primarily a Stata user, so package management is never something I've had to deal with. R users, how do you normally deal with the packages you always use?

Responses:



The fundamental packages we will use are the following (plus some extras): 

- Pandas: Data management
    - https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf
- Numpy: Matrix and array programing
    - https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf
- Scipy: More math stuff 
    - https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_SciPy_Cheat_Sheet_Linear_Algebra.pdf
- Matplotlib: Graphics
    - https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_Matplotlib_Cheat_Sheet.pdf
- Sympy: Symbolic math (Similar to Maple of Mathmatica)
    - http://daabzlatex.s3.amazonaws.com/9065616cce623384fe5394eddfea4c52.pdf
- statsmodels: Regression stuff


# Chapter 2 - Setting up Your Python Environment

Mostly about setting up Anaconda and using Jupyter (covered above).

They also talk about how to install packages. One way is using pip.

In [4]:
!pip install quantecon

Some of you may be thinking, "Why is there a little exclamation point at the beginning of that command?". In truth, I don't really know. I looked it up and it seems like it has something to do with pip being a shell command. I don't really know what that means. Does anyone else? The command seems to also work without the exclamation as well?

In [5]:
pip install quantecon

Note: you may need to restart the kernel to use updated packages.


So ¯\\\_(ツ)_/¯

You can also use the upgrade subcommand for pip:

In [6]:
pip install --upgrade quantecon

Requirement already up-to-date: quantecon in c:\users\bretd\anaconda3\lib\site-packages (0.4.5)
Note: you may need to restart the kernel to use updated packages.


They give you some basic commands:

In [7]:
pwd

'C:\\Users\\bretd\\Box\\PhD\\Python'

In [8]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4AC5-C707

 Directory of C:\Users\bretd\Box\PhD\Python

12/06/2019  11:23 AM    <DIR>          .
12/06/2019  11:23 AM    <DIR>          ..
12/06/2019  01:26 AM    <DIR>          .ipynb_checkpoints
07/11/2019  04:17 PM         (617,970) Cheat_sheet.pdf
07/19/2019  01:43 PM    <DIR>          Learning
12/06/2019  11:23 AM            26,670 Python_Group_Reading_Review.ipynb
07/11/2019  04:16 PM      (20,391,584) Quantitative Economics with Python.pdf
12/05/2019  10:11 PM             (684) test.ipynb
12/05/2019  10:16 PM              (14) test2.py
               5 File(s)     21,045,114 bytes
               4 Dir(s)  403,475,337,216 bytes free


In [9]:
run test.ipynb

Nice


In [10]:
cd C:\Users\bretd\Desktop

C:\Users\bretd\Desktop


In [11]:
pwd

'C:\\Users\\bretd\\Desktop'

In [12]:
cd C:\\Users\\bretd\\Box\\PhD\\Python

C:\Users\bretd\Box\PhD\Python


You can also save just the code from one cell as a file:

In [13]:
%%file test2.py
print(Niice)

Overwriting test2.py


In [14]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4AC5-C707

 Directory of C:\Users\bretd\Box\PhD\Python

12/06/2019  11:25 AM    <DIR>          .
12/06/2019  11:25 AM    <DIR>          ..
12/06/2019  01:26 AM    <DIR>          .ipynb_checkpoints
07/11/2019  04:17 PM         (617,970) Cheat_sheet.pdf
07/19/2019  01:43 PM    <DIR>          Learning
12/06/2019  11:27 AM            30,363 Python_Group_Reading_Review.ipynb
07/11/2019  04:16 PM      (20,391,584) Quantitative Economics with Python.pdf
12/05/2019  10:11 PM               684 test.ipynb
12/06/2019  11:26 AM                14 test2.py
               5 File(s)     21,048,807 bytes
               4 Dir(s)  403,475,091,456 bytes free


# Chapter 3 - An Introductory Example

This chapter uses an example to show you some more commands. I'm just going to show you those commands.

In [15]:
a = numpy.array([1,2,3])
a

NameError: name 'numpy' is not defined

In [16]:
import numpy

In [17]:
a = numpy.array([1,2,3])
a

array([1, 2, 3])

We can name numpy anything we want. That way we don't have to type it out every time:

In [18]:
import numpy as np
b = np.array([7,7,7])
b

array([7, 7, 7])

Arrays are cool things in Numpy that we will talk about later. They are basically vectors. We'll go more into Numpy later. 

There are packages, like numpy, but there are also subpackages:

In [19]:
x = np.random.randn(10)
x

array([ 0.09088725,  1.51097508,  0.14052667, -0.19673787,  0.86377817,
       -0.8030622 ,  0.49394908,  0.77685268,  0.21020867,  1.97482111])

This is how you do a loop in Python:

In [20]:
for i in range(5):
    print(i)

0
1
2
3
4


A couple things to note:
- The list starts at 0. This is because Python is indexed to 0. Any automatically made list in Python will start at 0. 
- You have to start your loop with ":". This is like "{" in Stata loops
- You HAVE to indent the first thing in your loop. Ending the indentation ends the loop.

We can also use *while* loops:

In [21]:
i = 0
while i < 5:
    print(i)
    i = i + 1


0
1
2
3
4


Can also say:

In [22]:
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


You can also loop over things like lists:

In [23]:
loop_lis = [2,3,4]
for i in loop_lis:
    print(i)

2
3
4


Have you had two lists of things and needed to map them? I have. Stata generally sucks at it. Python has a cool command called zip(). Check it out. 

In [24]:
names = ("Bret", "Oliver", "Gryffin")
nouns = ("human", "cat", "dog")

for name, noun in zip(names, nouns):
    print(f"{name} is a {noun}")


Bret is a human
Oliver is a cat
Gryffin is a dog


Where the "f" in the print function means format. It allows us to put variables in strings. 

There is a similar syntax to functions:

In [25]:
def cheez(x):
    print(x)

cheez("whiz")

whiz


Lets talk about lists. A list is just a collection of stuff. Any stuffs. This can be numbers, strings, or Boolean operators. They are convenient, albeit limited in some ways. If you want to use them like a vector, you're better off using numpy arrays because the operators work better. That said, here's a list: 

In [53]:
x = [1, "fish", 2, "fish", "red", "fish", True, "fish"]
x

[1, 'fish', 2, 'fish', 'red', 'fish', True, 'fish']

You can add things to a list by using the append *method*:

In [27]:
x.append("by Dr. Seuss")
x

[1, 'fish', 2, 'fish', 'red', 'fish', True, 'fish', 'by Dr. Seuss']

You can also get rid of the last thing in a list by using the pop method:

In [33]:
y = [1,2,3,4,5,6,7]
y.pop(-3)

5

In [31]:
x

[1, 'fish', 2, 'red', 'fish', True, 'fish']

To look at an individual element in a list:

In [34]:
x[0]

1

In [35]:
x[1]

'fish'

*List comprehensions* are also a cool part of Python. With a list comprehension, you can create list, like you would using a loop, but without the loop. The basic syntax of a list comprehension is:

[ expression for item in list if conditional ]

This is the same as:

for item in list:
    
    if conditional:
    
        expression

In [36]:
comp = [2 * i for i in range(10) if i != 6]
comp

[0, 2, 4, 6, 8, 10, 14, 16, 18]

We can also use larger conditional statements in Python:

In [40]:
def seperator(x):
    """
    This function seprtates a list into 3 lists that identify their data types
    """
    string = []
    inter = []
    boo = []
    list_len = len(x)
    for i in range(list_len):
        if type(x[i]) == str:
            string.append(x[i])
        elif type(x[i]) == int: 
            inter.append(x[i])
        else:
            boo.append(x[i])
    print(string) 
    print(inter) 
    print(boo)

seperator(x)

['fish', 'red', 'fish', 'fish']
[1, 2]
[True]


Where "len()" returns the length of list x, type() returns the type of variable the element is, and elif is shorthand for "else if". 

In [38]:
seperator?

In [39]:
seperator??

We can also combine if statements with "and":

In [41]:
def color(x):
    color = []
    for i in x:
        if type(i) == str and i != 'fish':
            color.append(i)
        else:
            pass
    return color

color(x)

['red']

We can also use "in" as an operator:

In [42]:
if 'fish' in x and 2 in comp:
    print('Nice')

Nice


# Chapter 4 - Python Essentials 

We've already touched on some of these topics, so I'll skip over some things. 

There are a few types of primitive data:
- String: Words
- Integer: Numbers with no decimals
- Float: Numbers with decimals 
- Boolean: T/F


With Boolean variables you can do Boolean algebra, if you'd like. Some basic Boolean things:

In [43]:
x = 1
y = 2

x < y

True

In [44]:
x > y

False

In [45]:
x == 2

False

In [46]:
x != 3

True

Along with lists, there are containers called *tuples*. Tuples are just lists that are "immutable", that is, you cannot change them:

In [51]:
lis = [1,2]
tup = ('1','2')
tup2 = (1,2)

lis[0] = 5
lis
type(tup2)

tuple

In [50]:
tup2[0] = 5
tup2

TypeError: 'tuple' object does not support item assignment

You can use *slice* notation to finish lists:

In [54]:
print(x)
print(x[3:5])
print(x[2:])
print(x[:4])
print(x[-2:])

[1, 'fish', 2, 'fish', 'red', 'fish', True, 'fish']
['fish', 'red']
[2, 'fish', 'red', 'fish', True, 'fish']
[1, 'fish', 2, 'fish']
[True, 'fish']


Another type of container is a dictionary. Dictionaries are like a list, but instead of indexing by a number, you index by a string. That string is called a *key*.

In [55]:
best_film_franchise = {'Name': 'Star Wars', 'Time': '3pm', 'Location': 'DeLoach'}
best_film_franchise['Time']

'3pm'

We also have a container called a *set*. These are collections of objects that do not repeat. You can do set operations with them. 

In [56]:
sett = {'a', 'b', 'b'}
sett

{'a', 'b'}

Lastly, some helpful functions:

In [57]:
max(1,2,3,4,100,5,6)

100

In [58]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

The command all sees if a list of Boolean statements are all True. The command any() sees if any statement out of a list is true.

In [59]:
x=1
y=2
True_1 = x<y
True_2 = x != y
False_1 = x > y
statements = (True_1, True_2, False_1)
all(statements)

False

In [60]:
any(statements)

True

In-line functions are a kind of confusing topic. Before, we named functions, like "separator". What if we didn't want to name the function? We just wanted to do it in-line? We could then use an anonymous function:

In [61]:
x**2

1

In [62]:
import scipy.integrate as sp
sp.quad?

In [63]:
sp.quad(x**3, 0,2)

ValueError: invalid callable given

In [64]:
sp.quad(lambda x: x**3,0,2)

(4.0, 4.440892098500626e-14)

# Next week?

Probably be good to read the chapters on:
- Numpy
- Matplotlib
- Scipy
- Pandas

Maybe do the exercises for the Pandas section as its probably the most relevant package? What do we think?  